### ISSUE TITLE
Transition between sand/gravel and grass glitched

### ISSUE THREAD

**Issue by Maxcension** [NovaWostra/Pixel-Perfection-Chorus-Eddit#1]
Hello!

I love your pack but i have a problem with the transition between sand/gravel and grass.
Here a screenshot (Optifine 1.17 pre20):
![2021-06-14_23 27 10](https://user-images.githubusercontent.com/10364593/121962360-f1165e80-cd68-11eb-9255-82d2d3df773c.png)

This problem doesn't affect transition between dirt and sand for example:
![2021-06-14_23 27 25](https://user-images.githubusercontent.com/10364593/121962455-0ab7a600-cd69-11eb-8528-ba7f0dad9660.png)

My settings:
![2021-06-14_23 25 57](https://user-images.githubusercontent.com/10364593/121962507-1e630c80-cd69-11eb-8bbf-d14c8f36c1f3.png)
![2021-06-14_23 25 46](https://user-images.githubusercontent.com/10364593/121962488-186d2b80-cd69-11eb-9f8e-20b9fd16c1cf.png)

Have a nice day and thanks! :)

**Comment by NovaWostra** [comment]
thats weird yea, some others told me about it but i was not able to
replicate it myself. I will try to fix it tomorrow. same as ravagers model
being messed up and birch doors

Maxime ***@***.***> schrieb am Mo., 14. Juni 2021, 23:35:

**Comment by Maxcension** [comment]
Hello!
Thank you for fixing the problem :)
