### ISSUE TITLE
Some sounds are stereo, which breaks directional audio

### ISSUE THREAD

**Issue by BeauGieskens** [NovaWostra/Pixel-Perfection-Chorus-Eddit#3]
There's a quirk in Minecraft where audio files need to be mono in order for directional audio and distance fall-off to work correctly. There are some sounds in this resource pack which are stereo, which causes them to play loudly as if they're coming directly from the player's head.

For example, I was recently playing on a multiplayer server where I could hear another player pressing a stone button from 1000 blocks away as if my face was sitting right beside it :smile:

If you're open to it, I'll go through and convert all the audio files to mono and submit a pull request.

**Comment by NovaWostra** [comment]
yea that would be awesome.

Beau Gieskens ***@***.***> schrieb am Mi., 1. Dez. 2021,
01:07:
