### ISSUE TITLE
Licensing Discrepancy

### ISSUE THREAD

**Issue by GeefireMC** [NovaWostra/Pixel-Perfection-Chorus-Eddit#5]
While the original Pixel Perfection is licensed under the [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/), this repository lacks a license, and the Curseforge page indicates that this pack is All Rights Reserved. My understanding of the original license is that it requires all derivative works to also use the same license, yet this pack lacks that license.
Probably not a huge deal, just figured I'd mention it, since it seems like an oversight.

**Comment by NovaWostra** [comment]
I've changed the licence on Curseforge to the correct licence. I had to use
the custom licence feature but I figured out how it works now! Thank you
for pointing it out.

Am Mi., 2. Feb. 2022 um 05:00 Uhr schrieb Geefire ***@***.***

**Comment by GeefireMC** [comment]
That's great! I've closed the issue now, thank you.
