### ISSUE TITLE
Version without New Sounds

### ISSUE THREAD

**Issue by Twitch0125** [NovaWostra/Pixel-Perfection-Chorus-Eddit#6]
First, I absolutely love that you're continuing this resource pack! I used it back in the day when XSSheep still worked on it.

Would it be possible to release a version without the custom sounds? 
or is there at least an easy way to disable the new sounds?

**Comment by NovaWostra** [comment]
yea there is an super easy way to disable them. go in Pixel Perfection
Legacy/assets/minecraft and delete the sounds folder.

Kaleb Ercanbrack ***@***.***> schrieb am Mi., 6. Apr. 2022,
07:28:

**Comment by Twitch0125** [comment]
Oh, awesome :)
