### ISSUE TITLE
CC-BY-SA 4.0 

### ISSUE THREAD

**Issue by temanogrel** [NovaWostra/Pixel-Perfection-Chorus-Eddit#8]
Is this pack also CC-BY-SA 4.0, like original Pixel Perfection, or not?

**Comment by NovaWostra** [comment]
Creative Commons Attribution-Share Alike 4.0 International License. http://creativecommons.org/licenses/by-sa/4.0/ yes

**Comment by temanogrel** [comment]
Thanks

**Comment by kno10** [comment]
Please add a LICENSE.txt or similar to the repository, to document this.
